version: "4.0"
services:
  app:
    build:
      args:
        user: zerowitt
        uid: 1000
      context: ./
      dockerfile: Dockerfile.dev
    working_dir: /var/www/
    environment:
      - COMPOSER_MEMORY_LIMIT=-1
    depends_on:
      - db
    volumes:
      - ./:/var/www
    networks:
      - zerowitt

  db_pgsql:
      image: postgres:latest
      env_file:
          -   .env
      volumes:
          -   dbdata:var/lib/postgresql
      ports:
          -   5432:5432

  db_mysq:
    image: mysql:5.7
    env_file:
        -   .env
    environment:
      MYSQL_DATABASE: tracetube
      MYSQL_ROOT_PASSWORD: tracetube
      MYSQL_PASSWORD: trcaetube
      MYSQL_USER: tracetube
      SERVICE_TAGS: dev
      SERVICE_NAME: mysql
    volumes:
      - dbdata:/var/lib/mysql
      - ./docker-compose/mysql/my.cnf:/etc/mysql/my.cnf
      - ./docker-compose/mysql/init:/docker-entrypoint-initdb.d
    ports:
      - 3307:3306
    networks:
      - zerowitt

  nginx:
    image: nginx:alpine
    ports:
      - 8005:80
    depends_on:
      - db
      - app
    volumes:
      - ./:/var/www
      - ./docker-compose/nginx:/etc/nginx/conf.d/
    networks:
      - zerowitt

networks:
  lahmi:
    driver: bridge

volumes:
  dbdata:
    driver: local

